#!/usr/bin/env bash
# tools/freestanding/gen-imports.sh — generate IMPORTS.md from the built fs-doom binary.
#
# Committed command (regenerate with: make imports).
# Lists every undefined (dynamic) symbol fs-doom pulls from libc/libm.
# These are the honest platform surface for rung 2 to eliminate or provide.
#
# Output: tools/freestanding/IMPORTS.md
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
BINARY="$SCRIPT_DIR/fs-doom"

if [[ ! -x "$BINARY" ]]; then
    echo "gen-imports: fs-doom not found — run 'make' first" >&2
    exit 1
fi

OUT="$SCRIPT_DIR/IMPORTS.md"

# Collect undefined symbols (dynamic imports).
# -u / --undefined-only: only undefined symbols.
# -D / --dynamic: scan the dynamic symbol table (for dynamic libs).
# For a dynamically linked binary, both are needed; also check static undefined.
UNDEFINED="$(nm -u "$BINARY" 2>/dev/null | awk '{print $2}' | sort -u || true)"

# Also capture ldd for library-level view.
LDD_OUT="$(ldd "$BINARY" 2>/dev/null || echo "(ldd not available)")"

cat > "$OUT" << 'HEREDOC_END'
# fs-doom IMPORTS.md — freestanding rung-1 libc surface

Generated by `bash tools/freestanding/gen-imports.sh` from the built `fs-doom`
binary.  These are the symbols that rung-2 (bare-metal) must either eliminate,
provide from a freestanding runtime, or implement as platform primitives.

**Command used**: `nm -u fs-doom | sort`

## Dynamic libraries linked

HEREDOC_END

echo '```' >> "$OUT"
echo "$LDD_OUT" >> "$OUT"
echo '```' >> "$OUT"
echo "" >> "$OUT"

cat >> "$OUT" << 'HEREDOC_END'
## Undefined symbols (nm -u fs-doom | sort)

HEREDOC_END

echo '```' >> "$OUT"
nm -u "$BINARY" | sort >> "$OUT"
echo '```' >> "$OUT"
echo "" >> "$OUT"

cat >> "$OUT" << 'HEREDOC_END'
## Symbol justifications

### Expected (core arithmetic — rung 2 must provide from compiler-rt / newlib):
HEREDOC_END

# Parse and annotate each symbol.
while IFS= read -r sym; do
    [[ -z "$sym" ]] && continue
    case "$sym" in
        __*x86*|__*i686*|__*muldi*|__*divdi*|__*udivdi*|__*moddi*|__*umoddi*)
            echo "- \`$sym\`: 64-bit arithmetic helper (compiler-rt / libgcc) — core fixed-point math (FixedDiv, FixedMul)" >> "$OUT" ;;
        memcpy|memmove|memset|memcmp|strlen|strcpy|strncpy|strcmp|strncmp|strcasecmp|strrchr|snprintf|sprintf|vsnprintf|sscanf)
            echo "- \`$sym\`: string/memory (newlib/musl) — expected; used in core and platform stubs" >> "$OUT" ;;
        malloc|free|calloc|realloc)
            echo "- \`$sym\`: heap (libc) — STRAGGLER: used in main() shim for WAD blob; NOT in I_ZoneBase/I_AllocLow (replaced with static arena)" >> "$OUT" ;;
        fopen|fclose|fread|fwrite|fseek|ftell|fprintf|fputc|fputs|printf|puts)
            echo "- \`$sym\`: stdio (libc) — STRAGGLER: used in main() shim (-sim file write) and I_Error; rung 2 replaces with fs_putc chain" >> "$OUT" ;;
        open|read|close|write|lseek)
            echo "- \`$sym\`: POSIX fd (libc) — SHIM: open/read/close in main() WAD load; write() is fs_putc (byte-out); rung 2 replaces open/read/close with host-specific loader" >> "$OUT" ;;
        clock_gettime)
            echo "- \`$sym\`: POSIX timer (libc) — used in I_GetTime / d_net.c; rung 2 replaces with hardware timer" >> "$OUT" ;;
        abort)
            echo "- \`$sym\`: process abort (libc) — I_Error fatal path; rung 2 replaces with spin-loop or hardware reset" >> "$OUT" ;;
        exit)
            echo "- \`$sym\`: process exit (libc) — I_Quit; rung 2 replaces with reset or power-off" >> "$OUT" ;;
        longjmp|setjmp|_setjmp|__longjmp)
            echo "- \`$sym\`: non-local jump (libc) — timedemo exit mechanism; rung 2 can replace with a flag-and-poll pattern" >> "$OUT" ;;
        sqrt|atan2|sin|cos|tan|fabs|floor|ceil|pow|log|exp)
            echo "- \`$sym\`: math (libm) — used in core (R_InitTables trig generation, archaeology §1); rung 2 provides from libm or boot-generates tables" >> "$OUT" ;;
        va_start|va_end|va_arg|__va_*)
            echo "- \`$sym\`: varargs (compiler) — I_Error vsnprintf; expected" >> "$OUT" ;;
        time|localtime|mktime)
            echo "- \`$sym\`: time (libc) — m_misc.c savegame timestamp; no-op stubs sufficient if saves unused" >> "$OUT" ;;
        *)
            echo "- \`$sym\`: [needs classification — see nm output above]" >> "$OUT" ;;
    esac
done <<< "$UNDEFINED"

echo "" >> "$OUT"
cat >> "$OUT" << 'HEREDOC_END'
## Rung-2 elimination path

| Category | Symbol(s) | Rung-2 action |
|----------|-----------|---------------|
| Heap (malloc/free) | malloc, free | Remove: WAD blob → static array; already done for I_ZoneBase/I_AllocLow |
| File I/O (open/read) | open, read, close | Remove: WAD delivered as ROM constant or linker symbol |
| Stdio | fopen, fprintf, etc. | Remove: route all output through fs_putc (UART); -sim flag unused |
| Timer | clock_gettime | Replace: hardware 35 Hz timer interrupt counter |
| Exit/abort | exit, abort | Replace: spin loop or hardware reset |
| setjmp/longjmp | setjmp, longjmp | Replace: flag-and-poll in main loop |
| String/mem | memcpy, memset, etc. | Provide: newlib/musl or hand-rolled stubs |
| Math | sqrt, atan2 | Provide: libm or boot-generate trig tables (bare-metal.md §4.1) |
| Compiler-rt | __*di* helpers | Provide: libgcc or compiler-rt (already present on ARM toolchain) |
HEREDOC_END

echo "" >> "$OUT"
echo "---" >> "$OUT"
echo "*Regenerate with: \`cd tools/freestanding && make imports\`*" >> "$OUT"

echo "gen-imports: wrote $OUT"
