#!/usr/bin/env node
// Generate engine/core/tables_fix.h: the packed correction stream that
// turns this toolchain's computed trig tables into the bit-exact 1993
// canon, plus the boot-verification checksum. Rerun after a toolchain
// (libm) change — the boot CRC will have told you.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const canon = JSON.parse(readFileSync(join(root, 'tools/golden/tables-canon.json')));

const createDoom = (await import(join(root, 'build/doom.js'))).default;
const doom = await createDoom({ print: () => {}, printErr: () => {} });
doom._web_gen_tables();

const SIZES = { finesine: 10240, finetangent: 4096, tantoangle: 2049 };
let out = `// GENERATED by tools/gen-tables.mjs — corrections that transform this
// toolchain's libm output into the bit-exact 1993 tables. Do not edit.
`;
let escTotal = 0, deltaTotal = 0;

Object.entries(SIZES).forEach(([name, n], which) => {
    const ptr = doom._web_table(which) >> 2;
    const raw = doom.HEAP32.subarray(ptr, ptr + n);
    const packed = new Uint8Array((n + 3) >> 2);
    const escapes = [];
    let deltas = 0;
    for (let i = 0; i < n; i++) {
        const d = canon[name][i] - raw[i];
        let code = 0;
        if (d === 1) code = 1;
        else if (d === -1) code = 2;
        else if (d !== 0) { code = 3; escapes.push(canon[name][i]); }
        if (code) deltas++;
        packed[i >> 2] |= code << ((i & 3) * 2);
    }
    deltaTotal += deltas; escTotal += escapes.length;
    console.log(`${name}: ${deltas} corrections (${escapes.length} escapes)`);
    out += `\nstatic const unsigned char fix_${name}[${packed.length}] = {${packed.join(',')}};\n`;
    out += `static const int fix_${name}_esc[${Math.max(1, escapes.length)}] = {${escapes.join(',') || 0}};\n`;
    out += `#define FIX_${name.toUpperCase()}_NESC ${escapes.length}\n`;
});

// FNV-1a over canon, identical to T_Checksum
let h = 0x811c9dc5;
for (const name of Object.keys(SIZES))
    for (const v of canon[name])
        h = Math.imul(h ^ (v >>> 0), 0x01000193) >>> 0;
out += `\n#define TABLES_CRC 0x${h.toString(16)}u\n`;

writeFileSync(join(root, 'engine/core/tables_fix.h'), out);
console.log(`total: ${deltaTotal} corrections, ${escTotal} escapes, CRC 0x${h.toString(16)}`);
console.log('wrote engine/core/tables_fix.h — rebuild to apply');